version: '3.4'

services:
  message-broker:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - main

  mapentitiesservice:
    image: ${DOCKER_REGISTRY-}mapentitiesservice
    build:
      context: .
      dockerfile: MapEntitiesService/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - message-broker
    networks:
      - main

networks:
  main:
    name: entities-network
