version: '3.4'

services:
  messageBroker:
    image: rabbitmq:3-management
    container_name: messageBroker
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - main

  minioDb:
    image: minio/minio
    container_name: minioDb
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    volumes:
      - C:\Docker\Data\MinIo:/data
    networks:
      - main

  mapentitiesservice:
    image: ${DOCKER_REGISTRY-}mapentitiesservice
    build:
      context: .
      dockerfile: MapEntitiesService/Dockerfile
    container_name: mapEntitiesService
    ports:
      - 50001:80
    depends_on:
      - messageBroker
    networks:
      - main

  mapsrepositoryservice:
    image: ${DOCKER_REGISTRY-}mapsrepositoryservice
    build:
      context: .
      dockerfile: MapsRepositoryService/Dockerfile
    container_name: mapsRepositoryService
    ports:
      - 50002:80
    depends_on:
      - minioDb
    networks:
      - main

  notificationsservice:
    image: ${DOCKER_REGISTRY-}notificationsservice
    build:
      context: .
      dockerfile: NotificationsService/Dockerfile
    container_name: notificationsService
    ports:
      - 50003:80
    depends_on:
      - messageBroker
    networks:
      - main

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    container_name: ApiGateway
    ports:
      - 55555:80
    networks:
      - main

networks:
  main:
    name: entities-network