version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    container_name: ApiGateway
    ports:
      - 55555:80
    networks:
      - main

  messageBroker:
    image: rabbitmq:3-management
    container_name: messageBroker
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - main

  minioDb:
    image: minio/minio
    container_name: minioDb
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    volumes:
      - C:\Docker\Data\MinIo:/data
    networks:
      - main

  seqService:
    image: datalust/seq:latest
    container_name: seqLoggerService
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80
      - 5341:5341
    volumes:
      - C:\Docker\Data\Seq:/data
    networks:
      - main

  mapentitiesservice:
    image: ${DOCKER_REGISTRY-}mapentitiesservice
    build:
      context: .
      dockerfile: MapEntitiesService/Dockerfile
    container_name: mapEntitiesService
    depends_on:
      - messageBroker
      - apigateway
    networks:
      - main

  mapsrepositoryservice:
    image: ${DOCKER_REGISTRY-}mapsrepositoryservice
    build:
      context: .
      dockerfile: MapsRepositoryService/Dockerfile
    container_name: mapsRepositoryService
    depends_on:
      - minioDb
      - apigateway
      - messageBroker
    networks:
      - main

  notificationsservice:
    image: ${DOCKER_REGISTRY-}notificationsservice
    build:
      context: .
      dockerfile: NotificationsService/Dockerfile
    container_name: notificationsService
    depends_on:
      - messageBroker
      - apigateway
    networks:
      - main

networks:
  main:
    name: entities-network